### ISSUE TITLE
Docker build

### ISSUE THREAD

**Issue by Marie-Donnie** [sbegaudeau/alma-m2-2017#6]
Bonsoir,

Nous avons toujours le même problème après l'avoir retourné dans tous les sens... Enfin, on arrive à changer l'erreur mais jamais à passer le build.

`
[ERROR] Failed to execute goal com.spotify:docker-maven-plugin:0.4.11:build (build-image) on project alma-server: Exception caught: Request error: POST unix://localhost:80/build?t=charlenemarie/alma-server: 500: HTTP 500 Internal Server Error -> [Help 1]
[...]
The command "mvn clean verify -f alma-server/pom.xml -e" exited with 1.
`
L'erreur nous renvoie vers cette page : https://cwiki.apache.org//confluence/display/MAVEN/MojoExecutionException

Voici la PR... qui a subi quelques changements. 
https://github.com/charlenemarie/alma-m2-2017/pull/12
On a changé les noms de l'organisation au cas où il y aurait des soucis à ce niveau. 
On a bien vérifié que les settings travis correspondaient à ceux d'autres groupes.
Rien n'y fait, on a dû manquer quelque chose mais en trois semaines on a toujours pas trouvé quoi.

Est-ce que vous verriez quelque chose d'évident ou non que l'on a juste manqué ?

**Comment by sbegaudeau** [comment]
Bonjour,

D'après ce que j'ai pu voir sur internet, le soucis peut être causé par un fichier Dockerfile incorrect. Sur le site du plugin maven docker de Spotify, on peut voir des exemples de soucis qui produirait la même erreur : https://github.com/spotify/docker-maven-plugin (en bas)

Sinon vous pouvez essayer de regarder si des logs d'erreurs plus précis sont disponibles dans ```/var/log/docker.log``` ou ```/var/log/upstart/docker.log```.

**Comment by Marie-Donnie** [comment]
Apparemment il nous manquait un mot-clé dans le dockerfile, et on ne l'avait pas vu parce que le commit était passé un peu avant sans problème. 

Merci pour l'aide !
